apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: vault-database
spec:
  provider: vault
  secretObjects:
    - secretName: secret-belajar-vault
      type: Opaque
      data:
        - key: database_username
          objectName: db-username
        - key: database_password
          objectName: db-password
  parameters:
    vaultAddress: "http://vault.default:8200"
    roleName: "database"
    objects: |
      - objectName: "db-username"
        secretPath: "secret/data/aplikasi-belajar"
        secretKey: "database_username"
      - objectName: "db-password"
        secretPath: "secret/data/aplikasi-belajar"
        secretKey: "database_password"